function _instanceof(a,b){return b!=null&&typeof Symbol!=="undefined"&&b[Symbol.hasInstance]?!!b[Symbol.hasInstance](a):a instanceof b}
function _typeof(a){"@babel/helpers - typeof";return _typeof=typeof Symbol==="function"&&typeof Symbol.iterator==="symbol"?function(a){return typeof a}:function(a){return a&&typeof Symbol==="function"&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":typeof a},_typeof(a)}
function _classCallCheck(a,b){if(!_instanceof(a,b))throw new TypeError("Cannot call a class as a function")}
function _defineProperties(a,b){for(var c=0;c<b.length;c++){var d=b[c];d.enumerable=d.enumerable||!1,d.configurable=!0,"value" in d&&(d.writable=!0),Object.defineProperty(a,d.key,d)}}
function _createClass(a,b,c){return b&&_defineProperties(a.prototype,b),c&&_defineProperties(a,c),a}
function _possibleConstructorReturn(a,b){return b&&(_typeof(b)==="object"||typeof b==="function")?b:_assertThisInitialized(a)}
function _assertThisInitialized(a){if(a===void 0)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");return a}
function _getPrototypeOf(a){return _getPrototypeOf=Object.setPrototypeOf?Object.getPrototypeOf:function(b){return b.__proto__||Object.getPrototypeOf(b)},_getPrototypeOf(a)}
function _inherits(a,b){if(typeof b!=="function"&&b!==null)throw new TypeError("Super expression must either be null or a function");a.prototype=Object.create(b&&b.prototype,{constructor:{value:a,writable:!0,configurable:!0}}),b&&_setPrototypeOf(a,b)}
function _setPrototypeOf(a,b){return _setPrototypeOf=Object.setPrototypeOf||function(b,c){return b.__proto__=c,b},_setPrototypeOf(a,b)}(function(){var a=['a','abbr','acronym','address','applet','area','article','aside','audio','b','base','basefont','bdi','bdo','bgsound','big','blink','blockquote','body','br','button','canvas','caption','center','cite','code','col','colgroup','command','content','data','datalist','dd','del','details','dfn','dialog','dir','div','dl','dt','em','embed','fieldset','figcaption','figure','font','footer','form','frame','frameset','h1','h2','h3','h4','h5','h6','head','header','hgroup','hr','html','i','iframe','image','img','input','ins','isindex','kbd','keygen','label','legend','li','link','listing','main','map','mark','marquee','menu','menuitem','meta','meter','multicol','nav','nextid','nobr','noembed','noframes','noscript','object','ol','optgroup','option','output','p','param','picture','plaintext','pre','progress','q','rb','rp','rt','rtc','ruby','s','samp','script','section','select','shadow','slot','small','source','spacer','span','strike','strong','style','sub','summary','sup','table','tbody','td','template','textarea','tfoot','th','thead','time','title','tr','track','tt','u','ul','var','video','wbr','xmp'];var b=function _loop(b){window._name=a[b],window._name=window._name[0].toUpperCase()+window._name.slice(1),a[b]=window._name,Ignite[window._name]=function(c){"use strict";function d(){var a;_classCallCheck(this,d);for(var b=arguments.length,c=new Array(b),e=0;e<b;e++)c[e]=arguments[e];return _possibleConstructorReturn(this,(a=_getPrototypeOf(d)).call.apply(a,[this].concat(c)))}
return _inherits(d,c),_createClass(d,[{key:"render",value:function render(c){return this.transform(document.createElement(a[b])),this.plainRender(c)}}]),d}(Ignite.Element),Object.defineProperty(Ignite[window._name],"name",{value:window._name})};for(var c in a)b(c);delete window._name})(window,document);
