function _instanceof(a,b){return b!=null&&typeof Symbol!=="undefined"&&b[Symbol.hasInstance]?!!b[Symbol.hasInstance](a):a instanceof b}
function _typeof(a){"@babel/helpers - typeof";return _typeof=typeof Symbol==="function"&&typeof Symbol.iterator==="symbol"?function(a){return typeof a}:function(a){return a&&typeof Symbol==="function"&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":typeof a},_typeof(a)}
function _classCallCheck(a,b){if(!_instanceof(a,b))throw new TypeError("Cannot call a class as a function")}
function _possibleConstructorReturn(a,b){return b&&(_typeof(b)==="object"||typeof b==="function")?b:_assertThisInitialized(a)}
function _assertThisInitialized(a){if(a===void 0)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");return a}
function _getPrototypeOf(a){return _getPrototypeOf=Object.setPrototypeOf?Object.getPrototypeOf:function(b){return b.__proto__||Object.getPrototypeOf(b)},_getPrototypeOf(a)}
function _inherits(a,b){if(typeof b!=="function"&&b!==null)throw new TypeError("Super expression must either be null or a function");a.prototype=Object.create(b&&b.prototype,{constructor:{value:a,writable:!0,configurable:!0}}),b&&_setPrototypeOf(a,b)}
function _setPrototypeOf(a,b){return _setPrototypeOf=Object.setPrototypeOf||function(b,c){return b.__proto__=c,b},_setPrototypeOf(a,b)}(function(){var c=["a","abbr","acronym","address","applet","area","article","aside","audio","b","base","basefont","bdi","bdo","bgsound","big","blink","blockquote","body","br","button","canvas","caption","center","cite","code","col","colgroup","command","content","data","datalist","dd","del","details","dfn","dialog","dir","div","dl","dt","em","embed","fieldset","figcaption","figure","font","footer","form","frame","frameset","h1","h2","h3","h4","h5","h6","head","header","hgroup","hr","html","i","iframe","image","img","input","ins","isindex","kbd","keygen","label","legend","li","link","listing","main","map","mark","marquee","menu","menuitem","meta","meter","multicol","nav","nextid","nobr","noembed","noframes","noscript","object","ol","optgroup","option","output","p","param","picture","plaintext","pre","progress","q","rb","rp","rt","rtc","ruby","s","samp","script","section","select","shadow","slot","small","source","spacer","span","strike","strong","style","sub","summary","sup","table","tbody","td","template","textarea","tfoot","th","thead","time","title","tr","track","tt","u","ul","var","video","wbr","xmp"];for(var a in c)window._name=c[a],window._name=window._name[0].toUpperCase()+window._name.slice(1),c[a]=window._name,Ignite[window._name]=function(a){"use strict";function b(a){return _classCallCheck(this,b),_possibleConstructorReturn(this,_getPrototypeOf(b).call(this,window._name,a))}
return _inherits(b,a),b}(Ignite.Node),Object.defineProperty(Ignite[window._name],"name",{value:window._name});delete window._name})(window,document)
